#!/bin/bash
yum -y install nfs-utils nfs-utils-lib
mkdir -p downloads
umount downloads
/etc/init.d/rpcbind restart
/etc/init.d/nfs restart
/etc/init.d/nfslock restart
mount 192.168.0.2:/export/downloads/Data/Siebel downloads

