#!/bin/sh
# chkconfig: 345 99 10
# description: start siebel services
#


case "$1" in
    'start')
        echo "Start Siebel Gateway"
        su -l siebel -c "source /opt/siebel/8.1.1.11.0/ses/gtwysrvr/siebenv.sh ; start_ns"
        echo "Start Siebel Server"
        su -l siebel -c "source /opt/siebel/8.1.1.11.0/ses/siebsrvr/siebenv.sh ; start_server all"
        echo "Start Siebel Webserver"
        su -l siebel -c "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/siebel/8.1.1.11.0/eappweb/bin ; \
                         export ORACLE_HOME=/opt/siebel/oracle/Middleware/Oracle_WT1 ; \
                         export ORACLE_INSTANCE=/opt/siebel/oracle/Middleware/Oracle_WT1/instances/instance1 ; \
                         /opt/siebel/oracle/Middleware/Oracle_WT1/opmn/bin/opmnctl startall"
        touch /var/lock/subsys/siebel_service
        ;;
    'stop')
        echo "Stop Siebel Webserver"
        su -l siebel -c "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/siebel/8.1.1.11.0/eappweb/bin ; \
                         export ORACLE_HOME=/opt/siebel/oracle/Middleware/Oracle_WT1 ; \
                         export ORACLE_INSTANCE=/opt/siebel/oracle/Middleware/Oracle_WT1/instances/instance1 ; \
                         /opt/siebel/oracle/Middleware/Oracle_WT1/opmn/bin/opmnctl stopall"
        echo "Stop Siebel Server"
        su -l siebel -c "source /opt/siebel/8.1.1.11.0/ses/siebsrvr/siebenv.sh ; stop_server all; mwadm stop"
        echo "Stop Siebel Gateway"
        su -l siebel -c "source /opt/siebel/8.1.1.11.0/ses/gtwysrvr/siebenv.sh ; stop_ns"
        rm -f /var/lock/subsys/siebel_service
        ;;
esac
