CREATE BIGFILE TABLESPACE "SDATA" DATAFILE '/u01/app/oracle/oradata/orcl/SDATA.dbf' SIZE 2G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/
exit
/
