CREATE BIGFILE TABLESPACE "SINDEX" DATAFILE '/u01/app/oracle/oradata/orcl/SINDEX.dbf' SIZE 10G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/
exit
/
